### ISSUE TITLE
Define sentences within Lean

### ISSUE THREAD

**Issue by sharma65** [vaibhavkarve/igl2020#13]
We want to be able to define sentences in Lean, which are formulas where every variable occurs bound. The way to do this will be to create ```var_list``` which will take in a formula and return a finite subset of the naturals that indexes which variables occur in the formula. This will be a recursive definition and will need to use the ```vars_in_term_t``` function. So the goal is to create the ```var_list``` function and then create a boolean ```is_sentence``` function which will map the ```var_is_bound``` function across the list, and then use this to define the subtype ```sentence``` analogously to how we have a subtype for admissible terms.

**Comment by sharma65** [comment]
http://builds.openlogicproject.org/open-logic-complete.pdf

Page 195 for a reference for sentences and free variables.

**Comment by vaibhavkarve** [comment]
Closed by #70
