### ISSUE TITLE
Interpret DLO inside of Lean

### ISSUE THREAD

**Issue by sharma65** [vaibhavkarve/igl2020#14]
The theory of DLO (dense linear orders) without endpoints has only a binary relation in its language and has axioms that state precisely the binary relation is a dense linear order. Create the ```DLO_lang``` inside Lean and create comments inside Lean for the axioms of DLO in first-order logic.

**Comment by sharma65** [comment]
http://builds.openlogicproject.org/open-logic-complete.pdf

Reference for DLO is page 356.

**Comment by vaibhavkarve** [comment]
`DLO_lang` is already defined in the file here: https://github.com/vaibhavkarve/igl2020/blob/158911bf2100fe79cec534e8f7dac38c0a93ab5b/src/model.lean#L200

 The next task is to fill in the definition of `LO_is_struc_of_DLO_lang` here: https://github.com/vaibhavkarve/igl2020/blob/158911bf2100fe79cec534e8f7dac38c0a93ab5b/src/model.lean#L390

**Comment by vaibhavkarve** [comment]
*Note:* since lean doesn't have the notion of DLOs we will only be showing that LO's are structures of the DLO language.
