### ISSUE TITLE
Change some defs to lemmas

### ISSUE THREAD

**Issue by vaibhavkarve** [vaibhavkarve/igl2020#4]
The Lean linter is reporting that some of the lemmas have been incorrectly marked as defs. This can be fixed easily.
Full list of defs that need to change:
```
/- The `def_lemma` linter reports: -/
/- INCORRECT DEF/LEMMA: -/
#print type_is_struc_of_set_lang /- is a lemma/theorem, should be a def -/
#print type_is_struc_of_ordered_set_lang /- is a lemma/theorem, should be a def -/
#print magma_is_struc_of_magma_lang /- is a lemma/theorem, should be a def -/
#print semigroup_is_struc_of_semigroup_lang /- is a lemma/theorem, should be a def -/
#print monoid_is_struc_of_monoid_lang /- is a lemma/theorem, should be a def -/
#print group_is_struc_of_group_lang /- is a lemma/theorem, should be a def -/
#print semiring_is_struc_of_semiring_lang /- is a lemma/theorem, should be a def -/
#print ring_is_struc_of_ring_lang /- is a lemma/theorem, should be a def -/
#print ordered_ring_is_struc_of_ordered_ring_lang /- is a lemma/theorem, should be a def -/
```
**Good challenge for anyone struggling to get more comfortable with git.**

**Comment by vaibhavkarve** [comment]
This is no more relevant. I am not sure which commit fixed this. But now the defs and lemmas are marked correctly.

**Comment by nikilravi** [comment]
I think it was in my commit- I actually ended up changing lemmas to defs instead of the other way around, it that fixed the lint errors. Not sure why, though...

**Comment by nikil-ravi** [comment]
I think it was in my commit- I actually ended up changing lemmas to defs instead of the other way around, and that fixed the lint errors. Not sure why, though...

**Comment by vaibhavkarve** [comment]
Ah. Thanks for pointing that out. I see now that this issue was titled incorrectly and was you did was indeed right.
